### ISSUE TITLE
Migrate repository to illumos org

### ISSUE THREAD

**Issue by pfmooney** [illumos/epoll-test-suite#1]
Considering development here as slowed, could this repository be migrated into the @illumos organization, where folks there can take over its maintenance?

cc: @numericillustration @jclulow

**Comment by jclulow** [comment]
I am totally on board with things like this going into the @illumos organisation!

**Comment by bahamat** [comment]
I'm looking into this.

**Comment by pfmooney** [comment]
> I'm looking into this.

Much appreciated!

**Comment by bahamat** [comment]
Nobody with objections on this side.

**Comment by pfmooney** [comment]
Thanks @bahamat (and anyone else @joyent who may have assisted).
